"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";

type BarRow = { symbol?: string; type?: string; strike?: number; last?: number; baseLast?: number; tradeTime?: string; expiration?: string; iv?: number; gamma?: number; volume?: number; openInterest?: number; };
type FeedEvent = { id: string; source: string; tier: string; signal: string; symbol?: string; tf?: string; price: number; side?: string; time?: string; receivedAt?: string; };
type Snapshot = { live?: boolean; rows?: BarRow[]; fetchedAt?: string; source?: string };
type MT5State = { live?: boolean; feeds?: Record<string, FeedEvent>; events?: FeedEvent[] };

const nfmt=(v:number,d=2)=>Number(v||0).toLocaleString(undefined,{maximumFractionDigits:d});
const clean=(v:number|undefined)=>typeof v==="number"&&Number.isFinite(v)?v:0;

export default function GoldLab(){
 const [csv,setCsv]=useState<Snapshot>({});
 const [mt5,setMt5]=useState<MT5State>({});
 const [now,setNow]=useState(new Date());
 useEffect(()=>{
  const loadLocal=()=>{try{const v=localStorage.getItem("gc-barchart-cache");if(v)setCsv(JSON.parse(v));const m=localStorage.getItem("gc-mt5-cache");if(m)setMt5(JSON.parse(m));}catch{}};
  loadLocal();
  const poll=async()=>{try{const r=await fetch("/api/mt5/state",{cache:"no-store"});const j=await r.json();if(j?.ok){setMt5(j);try{localStorage.setItem("gc-mt5-cache",JSON.stringify(j));}catch{}}}catch{}};
  poll();const id=setInterval(()=>{setNow(new Date());loadLocal();poll();},3000);return()=>clearInterval(id);
 },[]);
 const events=useMemo(()=>[...(mt5.events||[])].filter(e=>clean(e.price)>0).slice(0,60).reverse(),[mt5.events]);
 const rows=csv.rows||[];
 const feedPrice=mt5.feeds?.XAU1?.price||mt5.feeds?.XAU5?.price||events[events.length-1]?.price||0;
 const csvPrice=rows.find(r=>clean(r.baseLast)>0)?.baseLast||rows.find(r=>clean(r.last)>0)?.last||0;
 const price=feedPrice||csvPrice;
 const source=feedPrice?"MT5 SIGNAL PRICE":csvPrice?"BARCHART CSV":"WAITING FOR PRICE DATA";
 const chartValues=events.map(e=>clean(e.price));
 const chartPoints=chartValues.length>1?chartValues:rows.filter(r=>clean(r.last)>0).slice(0,40).map(r=>clean(r.last)).reverse();
 const min=chartPoints.length?Math.min(...chartPoints):0, max=chartPoints.length?Math.max(...chartPoints):1;
 const points=chartPoints.map((v,i)=>{const x=18+i*(964/Math.max(1,chartPoints.length-1));const y=270-(v-min)/(max-min||1)*220;return `${x},${y}`;}).join(" ");
 const feeds=Object.entries(mt5.feeds||{});
 return <main className="goldLab">
  <div className="labBackdrop"><i/><i/><i/><i/><i/><i/><i/></div>
  <header className="labTop"><Link href="/" className="labBack">← COMMAND CENTER</Link><div className="labWordmark"><span className="labOrb"/> AURUM / GOLD LAB <small>MARKET CONSOLE · 01</small></div><div className="labClock">{now.toLocaleTimeString()}</div></header>
  <section className="labHero"><div><p className="labEyebrow">LIVE MARKET WORKSPACE</p><h1>Gold, in <em>focus.</em></h1><p className="labIntro">One view for the latest gold price observations, your Barchart import, and MT5 signal intelligence.</p></div><div className="labPrice"><span>LAST OBSERVED GOLD PRICE</span><strong>{price?nfmt(price):"—"}</strong><div className="labPriceFoot"><i className={price?"pulse":"pulse idle"}/>{source}<span>{mt5.live?"· MT5 CONNECTED":"· AWAITING LIVE FEED"}</span></div></div></section>
  <section className="labGrid">
   <article className="labCard labChart"><div className="labCardHead"><div><small>PRICE TRACE</small><h2>Gold signal chart</h2></div><span className="labTag">{events.length>1?"MT5 EVENT PRICES":rows.length?"BARCHART ROWS":"NO DATA YET"}</span></div>
    <div className="chartWrap"><div className="chartAxis"><span>{max?nfmt(max):"—"}</span><span>{max&&min?nfmt((max+min)/2):"—"}</span><span>{min?nfmt(min):"—"}</span></div><svg viewBox="0 0 1000 300" preserveAspectRatio="none" role="img" aria-label="Chart of imported Barchart values or MT5 signal price observations"><defs><linearGradient id="goldFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#f4c96b" stopOpacity=".28"/><stop offset="100%" stopColor="#f4c96b" stopOpacity="0"/></linearGradient></defs>{[50,105,160,215,270].map(y=><line key={y} x1="18" y1={y} x2="982" y2={y} stroke="rgba(255,255,255,.09)" strokeDasharray="4 7"/>)}{chartPoints.length>1&&<><polygon points={`18,290 ${points} 982,290`} fill="url(#goldFill)"/><polyline points={points} fill="none" stroke="#f4c96b" strokeWidth="3" strokeLinejoin="round" strokeLinecap="round"/><circle cx={points.split(" ").at(-1)?.split(",")[0]} cy={points.split(" ").at(-1)?.split(",")[1]} r="5" fill="#fff2c6" stroke="#f4c96b" strokeWidth="3"/></>}</svg>{chartPoints.length<2&&<div className="chartEmpty"><span>◌</span><b>Chart is ready for your data</b><small>Import a Barchart CSV or wait for multiple MT5 price events.</small></div>}</div>
    <div className="chartFoot"><span><i className="legendGold"/> Price observations</span><span>{chartPoints.length} plotted points</span><span>Observed data only · no synthetic prices</span></div>
   </article>
   <article className="labCard labSignals"><div className="labCardHead"><div><small>MT5 INTELLIGENCE</small><h2>Signal status</h2></div><span className={mt5.live?"labLive":"labTag"}>{mt5.live?"LIVE":"STANDBY"}</span></div>
    {feeds.length?feeds.map(([key,f],i)=><div className="signalRow" key={key} style={{animationDelay:`${i*110}ms`}}><div className={"signalIcon "+(f.tier==="confirmed"?"isConfirmed":f.tier==="partial"?"isPartial":"")}>{key==="XAU1"?"1M":key==="XAU5"?"5M":key}</div><div className="signalText"><b>{f.symbol||key} <span>{f.tf||""}</span></b><small>{f.signal||"Waiting for signal details"}</small></div><div className="signalRight"><b>{nfmt(f.price)}</b><small>{(f.tier||"idle").toUpperCase()}</small></div></div>):<div className="labEmpty">No MT5 feeds received yet. This panel will populate automatically when your bridge reports.</div>}
   <div className="labSignalFoot"><span>EVENTS <b>{(mt5.events||[]).length}</b></span><span>CSV ROWS <b>{rows.length}</b></span><span>UPDATED <b>{now.toLocaleTimeString()}</b></span></div>
   </article>
   <article className="labCard labBarchart"><div className="labCardHead"><div><small>YOUR IMPORT</small><h2>Barchart market data</h2></div><span className={csv.live?"labLive":"labTag"}>{csv.live?"IMPORTED":"NOT LOADED"}</span></div><div className="dataStats"><div><span>ROWS</span><b>{rows.length}</b></div><div><span>SYMBOLS</span><b>{new Set(rows.map(r=>r.symbol).filter(Boolean)).size||"—"}</b></div><div><span>EXPIRIES</span><b>{new Set(rows.map(r=>r.expiration).filter(Boolean)).size||"—"}</b></div></div><div className="dataTableHead"><span>SYMBOL</span><span>TYPE</span><span>STRIKE</span><span>LAST</span></div><div className="dataRows">{rows.slice(0,7).map((r,i)=><div className="dataRow" key={i}><b>{r.symbol||"—"}</b><span>{r.type||"—"}</span><span>{r.strike?nfmt(r.strike,0):"—"}</span><span>{r.last?nfmt(r.last):"—"}</span></div>)}</div>{!rows.length&&<div className="labEmpty">Import your CSV on the Command Center. New imports are shared with this window.</div>}</article>
   <article className="labCard labRecent"><div className="labCardHead"><div><small>RECENT ACTIVITY</small><h2>Signal timeline</h2></div><span className="labTag">{events.length} PRICES</span></div><div className="timeline">{[...(mt5.events||[])].slice(0,6).map((e,i)=><div className="timelineRow" key={e.id||i}><span className="timelineDot"/><div><b>{e.source} · {(e.tier||"").toUpperCase()}</b><small>{e.signal}</small></div><strong>{nfmt(e.price)}</strong><time>{new Date(e.receivedAt||e.time||Date.now()).toLocaleTimeString()}</time></div>)}</div>{!(mt5.events||[]).length&&<div className="labEmpty">MT5 notifications will appear here as they arrive.</div>}</article>
  </section>
  <footer className="labFooter"><span>AURUM LAB <b>EXPERIMENTAL WORKSPACE</b></span><span>Market values are displayed from available MT5/Barchart data, not a guaranteed exchange feed.</span><Link href="/">RETURN TO COMMAND CENTER ↗</Link></footer>
  <style jsx global>{`
  .goldLab{--gold:#f4c96b;--labtext:#f2f0e9;--labmuted:#8e98a8;min-height:100vh;position:relative;isolation:isolate;overflow:hidden;padding:0 4vw 28px;background:#080b11;color:var(--labtext);font-family:Arial,sans-serif}
  .labBackdrop{position:absolute;inset:0;z-index:-1;overflow:hidden;pointer-events:none;background:radial-gradient(ellipse at 20% 0%,rgba(47,87,114,.22),transparent 38%),radial-gradient(ellipse at 90% 30%,rgba(160,111,39,.12),transparent 34%)}
  .labBackdrop i{position:absolute;width:34vw;height:34vw;border:1px solid rgba(244,201,107,.08);border-radius:50%;animation:labFloat 15s ease-in-out infinite alternate;left:calc(var(--i,1)*8%);top:calc(var(--i,1)*5%)}.labBackdrop i:nth-child(2n){width:20vw;height:20vw;animation-duration:19s;left:70%;top:12%}.labBackdrop i:nth-child(3n){animation-delay:-6s;left:35%;top:45%}
  @keyframes labFloat{from{transform:translate3d(-12px,-8px,0) scale(.94);opacity:.25}to{transform:translate3d(18px,14px,0) scale(1.08);opacity:.8}}
  .labTop{height:76px;display:flex;align-items:center;justify-content:space-between;gap:20px;border-bottom:1px solid rgba(255,255,255,.09)}.labBack,.labFooter a{color:#c8d0db;text-decoration:none;font-size:10px;letter-spacing:1.2px}.labWordmark{display:flex;align-items:center;gap:10px;font-size:12px;letter-spacing:2px;font-weight:700}.labWordmark small{font-size:9px;color:var(--labmuted);font-weight:400;letter-spacing:1px}.labOrb{width:9px;height:9px;background:var(--gold);border-radius:50%;box-shadow:0 0 20px var(--gold);animation:labPulse 2s infinite}.labClock{font-size:11px;color:var(--labmuted);font-variant-numeric:tabular-nums}
  @keyframes labPulse{50%{opacity:.4;box-shadow:0 0 4px var(--gold)}}
  .labHero{display:grid;grid-template-columns:1.1fr .9fr;gap:30px;align-items:end;padding:44px 0 32px;animation:labEnter .7s both}.labEyebrow,.labCardHead small{font-size:9px;letter-spacing:2px;color:var(--gold)}.labHero h1{font-size:clamp(34px,5vw,64px);line-height:1;margin:14px 0;font-weight:500;letter-spacing:-2px}.labHero h1 em{font-family:Georgia,serif;color:var(--gold);font-weight:400}.labIntro{max-width:480px;color:#9ba6b7;line-height:1.7;font-size:13px}.labPrice{border:1px solid rgba(244,201,107,.25);background:linear-gradient(120deg,rgba(244,201,107,.09),rgba(255,255,255,.015));padding:22px 24px;border-radius:12px;box-shadow:0 15px 60px rgba(0,0,0,.18)}.labPrice>span{display:block;font-size:9px;letter-spacing:1.6px;color:var(--labmuted)}.labPrice strong{display:block;font-size:clamp(34px,4vw,54px);font-weight:400;letter-spacing:-1.5px;margin:8px 0;color:#fff1c8;font-variant-numeric:tabular-nums}.labPriceFoot{display:flex;align-items:center;gap:7px;font-size:9px;color:#a6b0bd;flex-wrap:wrap}.pulse{width:6px;height:6px;background:#4df0a6;border-radius:50%;box-shadow:0 0 12px #4df0a6}.pulse.idle{background:#d2a34d;box-shadow:0 0 8px #d2a34d}
  .labGrid{display:grid;grid-template-columns:1.25fr .75fr;gap:14px}.labCard{min-width:0;background:linear-gradient(145deg,rgba(20,27,38,.92),rgba(12,16,24,.92));border:1px solid rgba(255,255,255,.085);border-radius:12px;padding:18px 18px 14px;box-shadow:0 16px 50px rgba(0,0,0,.13);animation:labEnter .75s both}.labCard:nth-child(2){animation-delay:100ms}.labCard:nth-child(3){animation-delay:180ms}.labCard:nth-child(4){animation-delay:260ms}@keyframes labEnter{from{opacity:0;transform:translateY(16px) scale(.99)}to{opacity:1;transform:translateY(0) scale(1)}}
  .labCardHead{display:flex;align-items:center;justify-content:space-between;gap:12px;margin-bottom:16px}.labCardHead h2{font-size:16px;font-weight:500;margin:6px 0 0;letter-spacing:-.2px}.labTag,.labLive{font-size:8px;letter-spacing:1px;padding:6px 8px;border-radius:4px;border:1px solid rgba(255,255,255,.12);color:#aeb7c4;white-space:nowrap}.labLive{color:#6cf0b1;border-color:rgba(108,240,177,.3);background:rgba(108,240,177,.06)}
  .labChart{grid-row:span 1}.chartWrap{height:260px;position:relative;padding-left:42px}.chartWrap svg{width:100%;height:100%;overflow:visible}.chartAxis{position:absolute;inset:8px auto 14px 0;display:flex;flex-direction:column;justify-content:space-between;font-size:9px;color:#7f8b9d;font-variant-numeric:tabular-nums}.chartEmpty{position:absolute;inset:0 0 0 42px;display:flex;flex-direction:column;align-items:center;justify-content:center;text-align:center;background:linear-gradient(90deg,transparent,rgba(10,15,23,.55),transparent);pointer-events:none}.chartEmpty span{font-size:28px;color:var(--gold);animation:labPulse 3s infinite}.chartEmpty b{font-size:12px;font-weight:500;margin:8px}.chartEmpty small{font-size:10px;color:var(--labmuted)}.chartFoot{display:flex;gap:14px;justify-content:space-between;flex-wrap:wrap;border-top:1px solid rgba(255,255,255,.07);padding-top:12px;margin-top:8px;color:#8995a6;font-size:9px}.chartFoot>span:first-child{color:#d6dce5}.legendGold{display:inline-block;width:13px;height:2px;background:var(--gold);vertical-align:middle;margin-right:5px}
  .signalRow{display:grid;grid-template-columns:40px minmax(0,1fr) auto;gap:10px;align-items:center;padding:13px 0;border-bottom:1px solid rgba(255,255,255,.065);animation:labEnter .55s both}.signalIcon{width:38px;height:34px;display:grid;place-items:center;background:rgba(111,174,225,.08);border:1px solid rgba(111,174,225,.2);border-radius:7px;font-size:10px;color:#83c8ff}.signalIcon.isConfirmed{color:#67f0ad;border-color:rgba(103,240,173,.3);background:rgba(103,240,173,.07)}.signalIcon.isPartial{color:var(--gold);border-color:rgba(244,201,107,.3)}.signalText{min-width:0}.signalText b,.signalRight b{display:block;font-size:11px;font-weight:600}.signalText b span{color:#7f8a9b;font-weight:400}.signalText small{display:block;color:#9ba6b7;font-size:10px;line-height:1.45;margin-top:5px;overflow-wrap:anywhere}.signalRight{text-align:right}.signalRight b{font-variant-numeric:tabular-nums}.signalRight small{display:block;color:var(--gold);font-size:8px;margin-top:5px;letter-spacing:.7px}.labSignalFoot{display:flex;justify-content:space-between;gap:8px;flex-wrap:wrap;margin-top:15px;font-size:8px;color:#8793a3}.labSignalFoot b{color:#e8edf4;margin-left:4px}
  .dataStats{display:grid;grid-template-columns:repeat(3,1fr);gap:8px;margin-bottom:18px}.dataStats div{background:rgba(255,255,255,.025);border:1px solid rgba(255,255,255,.06);border-radius:7px;padding:12px}.dataStats span{display:block;color:#8995a6;font-size:8px;letter-spacing:1px}.dataStats b{display:block;margin-top:7px;font-size:21px;font-weight:400}.dataTableHead,.dataRow{display:grid;grid-template-columns:1.2fr .7fr .8fr .8fr;gap:8px;padding:9px 4px;font-size:10px;border-bottom:1px solid rgba(255,255,255,.055)}.dataTableHead{font-size:8px;color:#7f8b9d;letter-spacing:1px}.dataRow span{color:#b8c1cd;font-variant-numeric:tabular-nums}.dataRow b{font-weight:500;overflow:hidden;text-overflow:ellipsis}.timelineRow{display:grid;grid-template-columns:8px minmax(0,1fr) auto;gap:10px;align-items:start;padding:10px 0;border-bottom:1px solid rgba(255,255,255,.06)}.timelineDot{width:6px;height:6px;border-radius:50%;background:var(--gold);margin-top:5px;box-shadow:0 0 8px rgba(244,201,107,.5)}.timelineRow div b{font-size:9px;display:block}.timelineRow div small{display:block;font-size:10px;color:#9aa6b5;line-height:1.4;margin-top:5px}.timelineRow strong{font-size:10px;font-weight:500}.timelineRow time{grid-column:2/4;font-size:8px;color:#738092}.labEmpty{padding:24px 10px;text-align:center;color:#8c98a8;font-size:11px;line-height:1.6}.labFooter{display:flex;justify-content:space-between;gap:16px;flex-wrap:wrap;padding:22px 0;color:#778394;font-size:9px;letter-spacing:.5px}.labFooter b{color:#d8dee8;margin-left:8px}.labFooter a{font-size:9px;color:var(--gold)}
  @media(max-width:850px){.labHero{grid-template-columns:1fr;padding:32px 0 24px}.labGrid{grid-template-columns:1fr}.labTop{height:auto;min-height:68px;flex-wrap:wrap;padding:14px 0}.labWordmark{order:-1;width:100%;justify-content:center}.labPrice{padding:17px}.chartWrap{height:220px}.labFooter{line-height:1.6}}
  @media(prefers-reduced-motion:reduce){.labBackdrop i,.labOrb,.labCard,.labHero,.signalRow{animation:none!important}}
  `}</style>
 </main>;
}
